### ISSUE TITLE
no global strapi after .reload

### ISSUE THREAD

**Issue by nkmnz** [pstaender/strapi-repl#1]
Hi, great project, helps a lot in development! :) unfortunately, I have to stop the repl and restart it each time I change a file, since the `.reload`-command leads to the following error on the next function call:
`Uncaught TypeError: Cannot read property 'services' of undefined`

I'm using mongo. Any idea what's wrong?

**Comment by pstaender** [comment]
Hi, @nkmnz glad you like it :)

Sry, I have no idea directly. It should work out-of-the-box. MongoDB shouldn't be an issue, either.

So you are using `strapi.services` on the prompt? What node and strapi version are you using? I would like to reproduce your problem.
